# Generated by Django 4.1.4 on 2023-03-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(max_length=25)),
                ('c_lname', models.CharField(max_length=25)),
                ('c_img', models.ImageField(upload_to='')),
                ('c_address', models.CharField(max_length=100)),
                ('c_area', models.CharField(max_length=50)),
                ('c_city', models.CharField(max_length=25)),
                ('c_state', models.CharField(max_length=25)),
                ('c_password', models.CharField(max_length=25)),
                ('c_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_fname', models.CharField(max_length=25)),
                ('f_lname', models.CharField(max_length=25)),
                ('f_img', models.ImageField(upload_to='')),
                ('f_address', models.CharField(max_length=100)),
                ('f_area', models.CharField(max_length=50)),
                ('f_city', models.CharField(max_length=25)),
                ('f_state', models.CharField(max_length=25)),
                ('f_password', models.CharField(max_length=25)),
                ('f_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_fid', models.CharField(max_length=25)),
                ('o_pid', models.CharField(max_length=25)),
                ('o_qty', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nutritionist_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_fname', models.CharField(max_length=25)),
                ('n_lname', models.CharField(max_length=25)),
                ('n_details', models.CharField(max_length=125)),
                ('n_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_oid', models.CharField(max_length=25)),
                ('pmt_amt', models.FloatField()),
                ('pmt_cid', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=25)),
                ('p_price', models.FloatField()),
                ('p_type', models.CharField(max_length=25)),
                ('p_img', models.ImageField(upload_to='')),
                ('p_desc', models.CharField(max_length=100)),
                ('p_isAvailable', models.BooleanField()),
            ],
        ),
    ]
