# Generated by Django 4.1.4 on 2023-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='c_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer_details',
            name='f_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer_order',
            name='o_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionist_details',
            name='n_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='pmt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='p_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer_order',
            name='o_fid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_order',
            name='o_pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='pmt_cid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='pmt_oid',
            field=models.IntegerField(),
        ),
    ]
