# Generated by Django 4.1.4 on 2023-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_alter_product_details_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='p_img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
